config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:create]
  resources :coments
  resources :donations
  post '/rate' => 'rater#create', :as => 'rate'
  resources :quotes, except: %i[new]
  get '/quotes/:publication_id/new', to: 'quotes#new', as: 'quote_new'
  resources :publications
  get "post", to: 'publications#make_post', as: 'post'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'profile/:id', to: 'users#show', as:'profile'
  resources :users, only: %i[edit update] 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'homes#index'

  get 'admin', to: 'rails_admin/main#dashboard', ass: "admin_user"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :rails_admin   
        can :read, :dashboard
      else
        can :read, :all
      end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent_category, class_name: "Category", foreign_key: "category_id", optional: true
    has_many :sub_categories, class_name: "Category", foreign_key: "category_id"
    has_many :publication_categories
end

app/models/coment.rb
class Coment < ApplicationRecord
    belongs_to :publication
    belongs_to :user
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :quote
  belongs_to :publication
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/publication.rb
class Publication < ApplicationRecord
    after_validation :report_validation_errors_to_rollbar
    has_many :quotes
    belongs_to :user
    has_many :coments
    has_many :publication_categories
    has_one_attached :image
    has_many :messages
    ratyrate_rateable :speed
end

app/models/publication_category.rb
class PublicationCategory < ApplicationRecord
  belongs_to :catergory
  belongs_to :publication
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
    belongs_to :publication
    has_many :messages
    after_validation :report_validation_errors_to_rollbar
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_one_attached :avatar
  has_many :quotes
  has_many :publications
  has_many :coments
  has_many :messages
  ratyrate_rater
  after_validation :report_validation_errors_to_rollbar

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show destroy edit update destroy  ]

  def index
    @user_quotes = current_user.quotes
  end

  def show
   
    @message = Message.new
    @messages = Message.where(publication: Publication.find(@quote.publication.id))
    # @messages = Message.joins(:quote).where("messages.user_id = ? ", current_user.id).where("messages.user_id = ? ",@quote.user.id).where("quotes.publication_id = ?", @quote.publication.id)
    @publication = Publication.find(@quote.publication.id)
  end

  def new
   @quote = Quote.new  
  end

  def create
    @quote = Quote.new(quote_params)  
    @quote.user_id= current_user.id
    @quote.publication_id = params[:quote][:publication_id]
    respond_to do |format|
      if @quote.save!
        format.html { redirect_to profile_path(current_user.id),notice: "Felicitacion has cotizado" }
        format.json { render :index, status: :created, location: @quote}
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to profile_path(current_user.id), notice: "Tu cotizacion fue actualizada"}
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end

  end



  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user.id), notice: "Cancelaste una cotizacion." }
      format.json { head :no_content }
    end
  end

  private
  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:date, :phone, :message)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/quotes/_form.html.erb
<div class="container text-center pb-3">
<%= form_with(model: @quote , local: true) do |f| %>
    <% if @quote.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este  no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @quote.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
<%= f.hidden_field :publication_id, value: params[:publication_id] %>




    <div class="form-group">
        <%= f.label 'Mensage' %>
        <%= f.text_area :message, class:"form-control" %>
    </div>
    <div class="container">
        <div class="form-group" >
        <%= f.label 'Fecha de tu evento' %>
        <%= f.date_field :date, class:"form-control" %>
    </div>
    <div class="form-group">
        <%= f.label 'Tu telefono' %>
        <%= f.text_field :phone, class:"form-control" %>
    </div>
    
    <div class = 'actions'>
        <%= f.submit "Cotizar", class:"btn btn-primary"  %>
    </div>
    
    
    </div>

    
<% end %>
</div>

app/views/quotes/_quotes.html.erb
<%# card%>
<div class="container">
        <div class="row">
            <%@user_quotes.each do |quote| %>
                <div class="col-3 px-2 pt-3 ">
                    <div class="card" style="width: 15rem;">
                        <div class="card-body">
                            <h5 class="card-title">Fecha del evento: <%= quote.date%></h5>
                            <p class="card-text">Mensaje: <%= quote.message  %></p>
                            <%= link_to 'Chat', quote,class:"btn btn-primary"%>
                            <%= link_to 'Editar', edit_quote_path(quote),class:"btn btn-primary" %>
                            <%= link_to 'Cancelar', quote,class:"btn btn-primary", method: :delete, data: { confirm: 'Deseas cancelar la publicacion?' } %>
                        </div>
                    </div>
                </div>
            <% end %>  
        </div>
    </div> 

app/views/quotes/edit.html.erb
<%= render "form", quotes: @quote %>

app/views/quotes/index.html.erb
<h1> Tus Cotizaciones</h1>

<table class ="table">
    <thead class ="table-dark">
        <tr>
        <th>Mensaje</th>
        <th>Phone</th>
        <th>Date</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <%= render "quotes/quotes" %>
    </tbody>
</table>

<br>

app/views/quotes/new.html.erb
<%= render 'form', quote: @quote  %>

app/views/quotes/show.html.erb
<div class="container pb-3">
    <h1 class="text-center"> Mensajes </h1>
<div class="container pt-2 shadow  rounded pb-2 w-50 border border-info">

    <div class="row" id="message">
    <div class="container ">
        
        <%@messages.each do |m| %>
        <% if m.user == current_user %>
            <div class="col-6">
            </div>
            <div class="col-6 text-center  shadow btn btn-primary  btn-sm border border-warning rounded-pill">
                 Tu Dices: 
                <h5><%= m.content %></h5>
            </div>
        <% else %>
            <div class="col-6 text-center ml-auto shadow bg-success btn-sm text-white border border-warning rounded-pill">
                Usuario Dice:
                <h5><%= m.content %></h5>
            </div>
            <div class="col-6">
            </div>
        <% end %>

    <% end %>
    </div>
</div>

</div>


<%= form_with(model: @message, local: true) do |f| %>
    <% if @message.errors.any? %>
        <div id = 'error_explanation'>
            <h2>Este  no se pudo crear por las siguientes razones</h2>
            <ul>
                <% @message.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.hidden_field :quote_id, value: params[:id] %>

    <div class="input-group mb-3 mt-2 w-50 container">
        <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-left-dots-fill" viewBox="0 0 16 16">
            <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm5 4a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm4 0a1 1 0 1 0-2 0 1 1 0 0 0 2 0zm3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2z"/>
            </svg></span>
        </div>
    <%= f.text_field :content, class:"form-control ", placeholder:"Mensaje" %>
    </div>

    <div class = 'actions  text-center'>
        <%= f.submit 'enviar',class:"btn btn-primary" %>
    </div>
<% end %>



</div>