config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:create]
  resources :coments
  resources :donations
  post '/rate' => 'rater#create', :as => 'rate'
  resources :quotes, except: %i[new]
  get '/quotes/:publication_id/new', to: 'quotes#new', as: 'quote_new'
  resources :publications
  get "post", to: 'publications#make_post', as: 'post'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'profile/:id', to: 'users#show', as:'profile'
  resources :users, only: %i[edit update] 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'homes#index'

  get 'admin', to: 'rails_admin/main#dashboard', ass: "admin_user"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :rails_admin   
        can :read, :dashboard
      else
        can :read, :all
      end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent_category, class_name: "Category", foreign_key: "category_id", optional: true
    has_many :sub_categories, class_name: "Category", foreign_key: "category_id"
    has_many :publication_categories
end

app/models/coment.rb
class Coment < ApplicationRecord
    belongs_to :publication
    belongs_to :user
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :quote
  belongs_to :publication
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/publication.rb
class Publication < ApplicationRecord
    after_validation :report_validation_errors_to_rollbar
    has_many :quotes
    belongs_to :user
    has_many :coments
    has_many :publication_categories
    has_one_attached :image
    has_many :messages
    ratyrate_rateable :speed
end

app/models/publication_category.rb
class PublicationCategory < ApplicationRecord
  belongs_to :catergory
  belongs_to :publication
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
    belongs_to :publication
    has_many :messages
    after_validation :report_validation_errors_to_rollbar
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_one_attached :avatar
  has_many :quotes
  has_many :publications
  has_many :coments
  has_many :messages
  ratyrate_rater
  after_validation :report_validation_errors_to_rollbar

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  
  def index
    @user_publications = current_user.publications
  end

  def edit
  end

  def make_post
    @publication = Publication.new 
    @coment = Coment.new
  end

  def create

    @publication = Publication.new(publication_params)
    #publicaciones pertenece a un usuario, por que lo necesita un id de usuarios
    #por lo que le pasamos el id del usuario que esta esta creando la publicacion
    #o sea, current_user
    @publication.user = current_user
    respond_to do |format|
      if @publication.save!
        PublicationMailer.with(publication: @publication).new_publication_email.deliver_later
        format.html { redirect_to profile_path(current_user.id), notice: "has publicado" }
        format.json { render :index, status: :created, location: @publication }
        
      else
        format.html { render :show, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
    
  end

  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to profile_path(current_user.id), notice: "La publicacion fue actualizada"}
        format.json { render :show, status: :ok, location: @publication }
        
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @publication.destroy
    respond_to do |format|
      format.html { redirect_to profile_path(current_user.id), notice: "Cancelaste una publicacion." }
      format.json { head :no_content }
    end
  end


  def show
    @coment = Coment.new
    @publications = Publication.all
    #publicaciones solo del current_user
    @user_publications = current_user.publications
    @coments = Coment.all
  
   
   

  end

  private
  def set_publication
    @publication = Publication.find(params[:id])
  end

  def publication_params
    params.require(:publication).permit(:title, :description, :value, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/publications/_form.html.erb
<%# formularioo de publicaciones %>
<div class="container text-center pb-3">
    <%= form_with(model: @publication , local: true) do |f| %>
        <% if @publication.errors.any? %>
            <div id = 'error_explanation'>
                <h2>Este  no se pudo crear por las siguientes razones</h2>
                <ul>
                    <% @publication.errors.full_messages.each do |msg|%>
                    <li><%= msg %></li>
                <% end %>
                </ul>
            </div>
        <% end %>



    
<%# input de titulo servicio %>
        <div class="form-group">
            <%= f.label "Titulo de tu servicio"%>
            <%= f.text_field :title, class:"form-control", placeholder:"Titulo de tu servicio" %>
        </div>
<%# input de describe tu servicio %>
        <div class="form-group">
            <%= f.label "Describe tu servicio" %>
            <%= f.text_area :description, class:"form-control",placeholder:"Describe tu servicio"%>
        </div>
<%# input de valor de tu servicio %>
        <div class="form-group">
            <%= f.label "Valores Desde"%>
            <%= f.text_field :value, class:"form-control", placeholder:"Valores Desde" %>
        </div>
<%# subir imagenes active storage %>
        <div class="field ">
            <%= f.label :imagen %><br />
            <%= f.file_field :image %>
        </div>
<%# creacion de publicacion %>
        <div class = 'actions'>
            <%= f.submit "Publicar", class:"btn btn-primary"  %>
        </div>
    
    <% end %>
</div>

app/views/publications/_mypublications.html.erb
<div class="container">
        <div class="row p-3">
            <%@user_publications.each do |publication| %>
                <div class=" shadow bg-white rounded col-3 p-3 m-3 ">
                    <div class="card" style="width: 15rem;">
                            <%= image_tag publication.image, class:"img-fluid" %>
                        <div class="card-body">
                            <h5 class="card-title"><%= publication.title %></h5>
                            <%= link_to 'Ver',publication,class:"btn btn-primary"%>
                            <%= link_to 'Editar', edit_publication_path(publication),class:"btn btn-primary" %>
                            <%= link_to 'Cancelar', publication,class:"btn btn-primary", method: :delete, data: { confirm: 'Deseas cancelar la publicacion?' } %>
                        </div>
                        <%publication.quotes.each do |q| %>
                            
                            <div class=" shadow bg-white pt-3">
                                <div class="card text-white bg-dark  mb-3" style="width: 15rem;">
                                    <div class="card-header">Cotizado por @º<%=q.user.name%></div>
                                    <div class="card-body">
                                        <p class="card-text"><%=q.user.name%> dice: <%=q.message %> </p>
                                        <p>Telefono: <%=q.phone %></p>   
                                        <p> Email: <%=q.user.email %></p>  
                                        <br>
                                        <%= link_to 'Chat',q,class:"btn btn-primary"%>
                                    </div>
                                </div>
                            </div>

                        <% end %>
                    </div>
                </div>
            <% end %>  
        </div>
    </div> 

app/views/publications/edit.html.erb
<%= render 'form', publication: @publication %>

app/views/publications/index.html.erb
<h1> Tus Publicaciones</h1>

<table class ="table">
    <thead class ="table-dark">
        <tr>
        <th>Titulo</th>
        <th>Descripcion</th>
        <th>Valor</th>
        <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
            <%= render "publications/mypublications" %>
    </tbody>
</table>

app/views/publications/make_post.html.erb
<div class="card mb-3 shadow p-1 mb-5 bg-white rounded">
    <%= render "publications/form" %>
</div>

app/views/publications/show.html.erb
<h1 class="text-center">Publicacion</h1>


<div class="accordion " id="accordionExample">
    <div class="card shadow p-3 mb-5 bg-white rounded">
        <div class="card-header" id="headingOne">
            <h2 class="mb-0">
                <button class="btn btn text-center btn btn-primary btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                <%=@publication.title%>
                </button>
            </h2>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class=" card-body">
                <div class="container card shadow p-3 mb-5 bg-white rounded">
                    <div class="row no-gutters ">
                        <div class="col m-3">
                            <%= link_to(image_tag(@publication.image.variant(resize: "400x400")), rails_blob_path(@publication.image, disposition: "attachment"))%>
                        </div>
                        <div class="col m-3">
                            <div class="card">
                                <div class="card-header">
                                    <%=@publication.user.name%> Publica:
                                </div>
                                <div class="card-body">
                                    <h5 class="card-title"><%=@publication.title%></h5>
                                    <p class="card-text"><%=@publication.description%></p>
                                    <%= link_to 'Cotizar', quote_new_path(@publication.id),class:"btn btn-primary"%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card shadow p-3 mb-5 bg-white rounded">
        <div class="card-header " id="headingTwo">
        <h2 class="mb-0">
            <button class="btn btn-danger text-center btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
            Contactos
            </button>
        </h2>
        </div>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">

        <h3 class="text-center">Correo electronico: <%=@publication.user.email %></h3>
            
        </div>
        </div>
    </div>
    <div class="card shadow p-3 mb-5 bg-white rounded">
        <div class="card-header" id="headingThree">
        <h2 class="mb-0">
            <button class="btn btn btn-info text-center btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="true" aria-controls="collapseThree">
            Valor desde
            </button>
        </h2>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
        <div class="card-body ">
           <h2 class="text-center"> $<%= @publication.value %> </h2>
        </div>
        </div>
    </div>
  

    <div class="card mb-3 shadow p-1 mb-5 bg-white rounded">
      Notas : <%= rating_for @publication, :speed %>
        <%= render "coments/form" %>
    </div>

     <div class="card mb-3 shadow p-1 mb-5 bg-white rounded">
        <%= render "coments/coment" %>
    </div>
</div>