config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:create]
  resources :coments
  resources :donations
  post '/rate' => 'rater#create', :as => 'rate'
  resources :quotes, except: %i[new]
  get '/quotes/:publication_id/new', to: 'quotes#new', as: 'quote_new'
  resources :publications
  get "post", to: 'publications#make_post', as: 'post'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'profile/:id', to: 'users#show', as:'profile'
  resources :users, only: %i[edit update] 
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root 'homes#index'

  get 'admin', to: 'rails_admin/main#dashboard', ass: "admin_user"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
      if user.admin?
        can :manage, :all
        can :access, :rails_admin   
        can :read, :dashboard
      else
        can :read, :all
      end


    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent_category, class_name: "Category", foreign_key: "category_id", optional: true
    has_many :sub_categories, class_name: "Category", foreign_key: "category_id"
    has_many :publication_categories
end

app/models/coment.rb
class Coment < ApplicationRecord
    belongs_to :publication
    belongs_to :user
end

app/models/donation.rb
class Donation < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :quote
  belongs_to :publication
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/publication.rb
class Publication < ApplicationRecord
    after_validation :report_validation_errors_to_rollbar
    has_many :quotes
    belongs_to :user
    has_many :coments
    has_many :publication_categories
    has_one_attached :image
    has_many :messages
    ratyrate_rateable :speed
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
    belongs_to :publication
    has_many :messages
    after_validation :report_validation_errors_to_rollbar
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
  has_one_attached :avatar
  has_many :quotes
  has_many :publications
  has_many :coments
  has_many :messages
  ratyrate_rater
  after_validation :report_validation_errors_to_rollbar

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name   # assuming the user model has a name
      # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails, 
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marketvisual</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Teko:wght@300&display=swap" rel="stylesheet"> 
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <%= render'shared/navbar'%>

     
    <div class="container margen">
      <%= yield %>
    </div>
    <%= render'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
    <!-- Footer -->
<footer class=" bg-blue text-center text-dark">
    <!-- Grid container -->
    <div class="container p-4">
        <!-- Section: Social media -->
        <section class="mb-4 ml-5">
        <!-- Facebook -->
       <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
        <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
        </svg>

        <!-- Twitter -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-twitter" viewBox="0 0 16 16">
        <path d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z"/>
        </svg>

        <!-- Google -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16">
        <path d="M15.545 6.558a9.42 9.42 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.689 7.689 0 0 1 5.352 2.082l-2.284 2.284A4.347 4.347 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.792 4.792 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.702 3.702 0 0 0 1.599-2.431H8v-3.08h7.545z"/>
        </svg>

        <!-- Instagram -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
        <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
        </svg>

        <!-- Linkedin -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
        <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854V1.146zm4.943 12.248V6.169H2.542v7.225h2.401zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248-.822 0-1.359.54-1.359 1.248 0 .694.521 1.248 1.327 1.248h.016zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016a5.54 5.54 0 0 1 .016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225h2.4z"/>
        </svg>

        <!-- Github -->
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
        </svg>
        </section>
        <!-- Section: Social media -->

        <!-- Section: Form -->
        <section class="">
        <form action="">
            <!--Grid row-->
            <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <!--Grid column-->

            <!--Grid column-->

            <!--Grid column-->

            <!--Grid column-->
            <!--Grid column-->
            </div>
            <!--Grid row-->
        </form>
        </section>
        <!-- Section: Form -->

        <!-- Section: Text -->
        <section class="mb-4">
        <h3>MARKETVISUAL</h3>
        <p>
            Aplicacion web de busqueda y publicaciones de servicios para profesionales del area audivisual , sonido y musicos profesionales ,los usuarios que utilicen esta aplicacion podran evaluar y comentar los servicios y cursos entregados por los profesionales. los profesionales podran publicar sus servicios indicando los valores . Los usuarios podran cotizar y publicar. APP específicamente para profesionales del área audiovisual, sonido y músicos profesionales.
        </p>
        </section>
        <!-- Section: Text -->

        <!-- Section: Links -->
        <section class="">
        <!--Grid row-->
        <div class="row">
            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled mb-0">
                <li>
                <a href="#!" class="text-dark">Link 1</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 2</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 3</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 4</a>
                </li>
            </ul>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled mb-0">
                <li>
                <a href="#!" class="text-dark">Link 1</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 2</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 3</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 4</a>
                </li>
            </ul>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled mb-0">
                <li>
                <a href="#!" class="text-dark">Link 1</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 2</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 3</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 4</a>
                </li>
            </ul>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled mb-0">
                <li>
                <a href="#!" class="text-dark">Link 1</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 2</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 3</a>
                </li>
                <li>
                <a href="#!" class="text-dark">Link 4</a>
                </li>
            </ul>
            </div>
            <!--Grid column-->
        </div>
        <!--Grid row-->
        </section>
        <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2021 Copyright:
        <a class="text-dark" href="https://mdbootstrap.com/">MARKETVISUAL</a>
    </div>
    <!-- Copyright -->
</footer>
<!-- Footer -->
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-orange fixed-top">
<a class="navbar-brand animation-target " href="#"><%root_path%><svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-chart-candle" width="44" height="44" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
  <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
  <rect x="4" y="6" width="4" height="5" rx="1" />
  <line x1="6" y1="4" x2="6" y2="6" />
  <line x1="6" y1="11" x2="6" y2="20" />
  <rect x="10" y="14" width="4" height="5" rx="1" />
  <line x1="12" y1="4" x2="12" y2="14" />
  <line x1="12" y1="19" x2="12" y2="20" />
  <rect x="16" y="5" width="4" height="6" rx="1" />
  <line x1="18" y1="4" x2="18" y2="5" />
  <line x1="18" y1="11" x2="18" y2="20" />
</svg>MARKETVISUAL<%root_path%></a>

<% if  user_signed_in? %>
     <!-- imagen de perfil-->
    <a class="navbar-brand " href="#"><%=image_tag current_user.avatar,:class =>"img-fluid rounded-circle navimg border border-danger ml-4"%><a>
    <!-- menu de perfil-->
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">Hola@<%= current_user.name%>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#"><%= link_to '  Perfil', profile_path(current_user.id), class:"nav-link text-secondary " %></a>
        </li>
    </ul>
</div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse " id="navbarNav">

            
            <ul class="navbar-nav ml-auto">
                <!-- barra de busqueda y boton-->
        <%= form_with(url:root_path, method: :get, local: :true, class: 'form-inline') do %>
        <%= text_field_tag :q, "", class: 'form-control mr-sm-1' %>
        <%= submit_tag( "Buscar", Class: 'btn btn-outline-dark my-1 my-sm-0 ' )%>
<%end%>
               
                <li class="nav-item">
                    <%= link_to 'Home', root_path, class:"nav-link" %>
                </li>
                 <% if current_user.admin? %>
                    <%= link_to 'Perfil Administrador', admin_path,class:"nav-link" %>
                <%end%>
                <li class="nav-item">
                    <%= link_to 'Publicar', post_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Donar', new_donation_path, class:"nav-link" %>
                </li>
                <li>
                    <%= link_to 'Salir', destroy_user_session_path, method: :delete, class:"nav-link" %>
                </li>
                
                

            </ul>
            
<%else%>
            <!-- vista de navbar de visitas y usarios-->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <%= link_to 'Registrate',new_user_registration_path, class:"nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Inicia Sesion',user_session_path, class:"nav-link" %>
                </li>
    
            </ul>
<% end %>
    </div>

</nav>